/**
 **************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************************************************************
 */
#include <stdint.h>
typedef volatile unsigned int vuint32_t ;
#define RCC_BASE 0X40021000
#define PortA_BASE 0X40010800
#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE + 0X18))
#define GPIOA_CRH  *((volatile uint32_t*)(PortA_BASE+ 0X04))
#define GPIOA_ODR  *((volatile uint32_t*)(PortA_BASE+ 0X0c))
typedef union {
 vuint32_t allfields;
 struct{
  vuint32_t reserved:13;
  vuint32_t pin13 :1;
 }pin;
}R_ODR_t;
volatile R_ODR_t * R_ODR=(volatile R_ODR_t*)(PortA_BASE + 0X0c);
unsigned char g_variable[3] ={1,2,3};
unsigned char const const_variable[3]={1,2,3};

int main(void){
 RCC_APB2ENR |= 1<<2 ;
 GPIOA_CRH &= 0xff0fffff ;
 GPIOA_CRH |=0x00200000;
 while(1){
  R_ODR->pin.pin13 =1;
  //GPIOA_ODR |= 1<<13; //SET BIT 13
  for(int i=0;i<5000;i++);
  //GPIOA_ODR &= ~(1<<13);//clear bit 13
  R_ODR->pin.pin13 =0;
  for(int i=0;i<5000;i++);
 }
 return 0;
}